name: CI Pipeline

# Quando rodar?
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  go-check:
    name: Check Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' #1.25 ou maior
          cache: true # Deixa as bibliotecas usadas em cache

      - name: Download Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./... # Roda os arquivos *_test.go

      - name: Verify Build
        run: go build -v ./cmd/library-scraper/main.go

  docker-check:
    name: Check Docker Build
    runs-on: ubuntu-latest
    needs: go-check # So roda se o Go passar
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        # Tenta buildar o Dockerfile inteiro
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Bloqueia o push para o docker hub
          tags: notion-scraper:test
          # Cache para lembrar do alpine e do chromium
          cache-from: type=gha
          cache-to: type=gha,mode=max