name: CI Pipeline

# Quando rodar?
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  go-check:
    name: Check Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.25' #1.25 ou maior

      - name: Download Dependencies
        run: go mod download

      - name: Verify Build
        run: go build -v ./...

  docker-check:
    name: Check Docker Build
    runs-on: ubuntu-latest
    needs: go-check # So roda se o Go passar
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        # Tenta buildar o Dockerfile inteiro
        # Bloqueia o push para o docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: notion-scraper:test